# Generated by Django 2.2 on 2022-01-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200, verbose_name='Нефтебаза')),
                ('objectid', models.CharField(max_length=200, verbose_name='Резервуар')),
                ('productid', models.PositiveIntegerField(verbose_name='Продукт')),
                ('shiftnumber', models.CharField(max_length=200, verbose_name='Номер смены')),
                ('shiftbegt', models.DateTimeField(verbose_name='Дата и время начала рабочей смены')),
                ('shiftendt', models.DateTimeField(verbose_name='Дата и время окончания рабочей смены')),
                ('attrval_start_weight', models.PositiveIntegerField(verbose_name='Масса на начало смены')),
                ('attrval_end_weight', models.PositiveIntegerField(verbose_name='Масса на конец смены')),
                ('acceptance_sum', models.PositiveIntegerField(verbose_name='Суммарная масса принятого нефтепродукта')),
                ('shipment_sum', models.PositiveIntegerField(verbose_name='Суммарная масса отгруженного нефтепродукта')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Версия пакета выгрузки по рабочей смене')),
                ('index', models.PositiveSmallIntegerField(unique=True, verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Отклонение',
                'verbose_name_plural': 'Отклонения',
            },
        ),
    ]
